### ISSUE TITLE
Empanada plugin fails to install

### ISSUE THREAD

**Issue by JemimaBurden** [volume-em/empanada-napari#13]
I have installed Napari, but empanada fails to install. I have tried from install by name and from the available plugins menu, as well as via pip (although with pip I think there are other issues there for my set up). I can share the error messages if helpful. Many thanks and best wishes, Jemima

**Comment by conradry** [comment]
Hi Jemima,

The error messages would be very helpful.

Just a few other things to confirm:

1. What Python version are you using?
2. Did you install napari into a conda environment?
3. What platform are you using (Mac, Linux, Windows)?

Best,
Ryan

**Comment by conradry** [comment]
It looks like the problem is related to the Python 3.10 installation you have. My guess is the you're not switched into the right conda environment. Check the output for the command ```pip --version```. Does it say Python 3.10?

Regardless, the first thing to try is installing in a clean conda environment:

```
conda create -n empanada python==3.9
conda activate empanada
pip install empanada-napari
```

Hopefully, that works!

**Comment by JemimaBurden** [comment]
Thanks...
The output from pip version suggests it is 3.9, but I tried to do (I think) what you suggested and got an error. - see copy of command session below:

C:\Users\Jemima>pip --version
pip 21.2.4 from C:\USers\Jemima\miniconda3\lib\site-packages\pip (python 3.9)

C:\Users\Jemima>conda create -n empanada python==3.9
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https://conda.anaconda.org/conda-forge/win-64'

**Comment by conradry** [comment]
Huh. Sorry this is such a pain.

The [official conda docs](https://docs.anaconda.com/anaconda/user-guide/troubleshooting/?highlight=CondaHTTPError%3A%20HTTP%20000%20CONNECTION%20FAILED#http-000-connection-failed) suggest trying this command:

```conda config --set ssl_verify false```

**Comment by JemimaBurden** [comment]
Thanks - Tried and repeated the create ... and got the same error.

Tried again from inside napari with no joy... any more suggestions? 

FYI will also try on another computer..(fingers crossed)

**Comment by conradry** [comment]
Your original problem was with installing the numcodecs package (which is a dependency of zarr). It looks like installing [zarr through pip can sometimes be unreliable](https://github.com/zarr-developers/numcodecs/issues/70). Take a stab at installing it with conda instead and then try installing empanada-napari:

```
conda install -c conda-forge zarr
pip install empanada-napari
```

As for creating a new environment, the HTTP 000 errors appears to be fairly common for conda and there are a few different causes. Some possible solutions are given [here](https://stackoverflow.com/questions/50305725/condahttperror-http-000-connection-failed-for-url-https-repo-continuum-io-pk).

**Comment by JemimaBurden** [comment]
Thank you -  I tried that on my PC still with no joy. This said, I have now got it installed on another PC so am tempted to not spend too much time troubleshooting my PC's problems. Do you want me to close the issue or not? Also, I have a couple of questions regarding segmentation export (works for 3D but not the same for 2D?)... should I raise a separate issue, or email you or Kedar?

**Comment by conradry** [comment]
Glad to hear you got the plugin working! My last suggestion, if you really want napari to run on that one PC, would be to try installing napari as a [bundled app](https://napari.org/tutorials/fundamentals/installation#install-as-a-bundled-app).

Go ahead and create a separate issue for the segmentation export questions, that way there's a public record for anyone else who encounters the same problems.

**Comment by JemimaBurden** [comment]
Thanks will do...🙂
