### ISSUE TITLE
feature request: progress bars during segmentation

### ISSUE THREAD

**Issue by kevinyamauchi** [volume-em/empanada-napari#25]
Hello! I think it would would be nice if there were some progress bars in the UI during segmentation (and any other long computations) so the user knows that empanada is still working. In case it is helpful, I have pasted links to a few examples with progress bars below. Thanks!

- https://github.com/napari/napari/blob/main/examples/mgui_with_threadworker_.py
- https://github.com/napari/napari/blob/main/examples/progress_bar_threading_.py
- https://github.com/napari/napari/blob/main/examples/progress_bar_segmentation_.py

**Comment by conradry** [comment]
Hi Kevin,

I added a simple indefinite progress bar like the first example to both 2D and 3D inference. It works great!

Thanks again,
Ryan
