### ISSUE TITLE
empanada plug-in not appearing in Napari drop-down menu after Conda pip install 

### ISSUE THREAD

**Issue by sgridolfi** [volume-em/empanada-napari#5]
Hi,

I have installed as suggested, by using the Anaconda prompt with pip install. 
But then, after installation, the plug-in does not appear in the drop-down menu of my Napari.

How shall I resolve this?

Thank you,
Cheers,
Sgridolfi

**Comment by conradry** [comment]
Hi Sgridolfi,

Can you check to see if there was an error in loading the plugin? In Napari, click the Plugins drop-down. Select Plugin Errors and click the drop-down where it says "select plugin...". Is empanada-napari there, if so what does the error message say?

**Comment by sgridolfi** [comment]
Hi conradry,

thank you for your reply. I checked and nothing shows in the plugins error tab.

Thank you for your support

![Capture](https://user-images.githubusercontent.com/101745228/158683067-c5b25a0a-d583-4ece-8b9d-9efa93037c6b.PNG)

**Comment by conradry** [comment]
Just to confirm, the commands you ran from Anaconda prompt were:

```shell
python -m pip install "napari[all]"
pip install empanada-napari
```

If so, it's sometimes the case that there are multiple installations of python and that napari and empanada-napari are installed in different virtual environments. Did you create any virtual environments during install?

A quick test to see if napari and empanada-napari are in the same python installation:

1. Type "python" in command prompt to open a new python shell.
2. Run:

```python
import napari
import empanada_napari
```

If that succeeds, then I would suggest that you try installing empanada-napari directly in napari from the "Install/Uninstall Plugins…" menu (see https://empanada.readthedocs.io/en/latest/empanada-napari.html)
