### ISSUE TITLE
Suggestion: add napari explicitly to your dependencies.

### ISSUE THREAD

**Issue by tlambert03** [volume-em/empanada-napari#6]
While running some tests for [npe2](https://github.com/napari/npe2), this plugin was among those that could not be imported after installation without also manually installing napari.  Even if it may seem obvious that a user of this plugin would already have napari installed, if your package imports anything directly from napari (including, e.g. `napari.types`), then you should add napari to your `install_requires` in setup.cfg/py.

thanks!

**Comment by conradry** [comment]
Done (v0.1.3)!
